.INCLUDE /usr/pack/ihp-sg13-kgf/open_ihp_sg13cmos5l/sg13cmos5l_stdcell/v0.1/cdl/sg13cmos5l_stdcell.cdl
.INCLUDE /usr/pack/ihp-sg13-kgf/eth/ez130_8t_stdcell/v1.0/cdl/ez130_8t.cdl
.INCLUDE /usr/pack/ihp-sg13-kgf/open_ihp_sg13cmos5l/sg13cmos5l_io/v0.1/cdl/sg13cmos5l_io.cdl
.INCLUDE /usr/pack/ihp-sg13-kgf/open_ihp_sg13cmos5l/sg13cmos5l_io/v0.1/cdl/source.added
.INCLUDE /usr/pack/ihp-sg13-kgf/open_ihp_sg13g2/sg13g2_sram/v2.2/cdl.dz/RM_IHPSG13_1P_1024x64_c2_bm_bist.cdl
